### ISSUE TITLE
Search does not work within code segments

### ISSUE THREAD

**Issue by vinckr** [ory/docusaurus-template#61]
This is not a huge issue, but could improve usability of the documentation somewhat. 

You cant search for terms that are within

 ``` code segments like this one ```

Some users would search for an API endpoint for example or some code snippet. Most of the time you still find the right document, but not always. 
Since the information is in there anyway, maybe there is a quick fix possible to make the code segments searchable?

**Comment by aeneasr** [comment]
I tried fixing this but it's very difficult due to the way code highlighting works. Another problem is that code blocks are hard to index using full text search as they have so many special chars like `<={}[]/&`. While I think that it is possible it will be very hard to get right. If you want to give it a shot, apparently we can use this tool to check the indexing stuff: https://docsearch.algolia.com/docs/run-your-own/

**Comment by vinckr** [comment]
I will have a look at it when I have some time. 
But I would close the issue for now and re-open when this is more concrete. 
It does not seem to be a critically important issue.
